name: 'data_eng_dbt'
version: '1.0.0'
config-version: 2

profile: 'dbt_poc'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  data_eng_dbt:
    +database: DATA_ENG_DBT
    +schema: DBT_BRONZE
    +quote_columns: true

models:
  data_eng_dbt:
    staging:
      +schema: DBT_BRONZE
      +materialized: view
    intermediate:
      +schema: DBT_BRONZE
      +materialized: view
    silver:
      +schema: DBT_SILVER
      +materialized: table

flags:
  require_generic_test_arguments_property: true
